### ISSUE TITLE
Stop container before exiting the driver

### ISSUE THREAD

**Issue by dvitale199** [mgibbs1259/gigantum_testing#19]
**Motivation**
All containers remain open after each run of create_project.py until cleanup-projects.py is run. The open containers are limiting the ability for subsequent runs.

**Plan**
We need a line at the end of each test to stop the container and assert that it is stopped.

**Suggestion**
Stop the container directly from the UI and assert the status as "Stopped" from the container status button in the top right of the screen

**Comment by billvb** [comment]
Closed per PR - each test is now responsible for closing the project container (that is, if it starts one)
