### ISSUE TITLE
Refactor CreateProject Class to Utility Methods

### ISSUE THREAD

**Issue by dvitale199** [mgibbs1259/gigantum_testing#21]
**Motivation**
create_project.py currently contains all of the test scripts. CreateProject() needs to be broken up into different files containing scripts with related functionality

**Plan**
Break up CreateProject() class into the following:

**driver.py:**
_driver_

**_testutils (directory)_**
**projectstartup.py:**

```
class StartupProject():
    def __init__ (self, driver):
	
    def log_in(self):

    def remove_guide(self):
	
    def create_project_no_base(self):
```

**projectoptions.py:**

```
class ProjectBases():
	
	def py2_min_base():

	def py3_min_base():
	
	def py3_ds_base():
		
	def r_tidy_base():

class ProjectPackageInstaller():

	def pip_package():

	def conda3_package():

	def apt_package():

class ProjectCustomDocker():

	def valid_custom_docker_instructions():

	def invalid_custom_docker_instructions():
```

**_Gigantumtests (directory)_**

_Playbook for each section of test plan_

**Comment by billvb** [comment]
Closed per PR
